/// <reference path="../jqwidgets.d.ts" />
import { EventEmitter, ElementRef, OnChanges, SimpleChanges } from '@angular/core';
import * as i0 from "@angular/core";
export declare class jqxFileUploadComponent implements OnChanges {
    attrAutoUpload: boolean;
    attrAccept: string;
    attrBrowseTemplate: string;
    attrCancelTemplate: string;
    attrDisabled: boolean;
    attrFileInputName: string;
    attrLocalization: jqwidgets.FileUploadLocalization;
    attrMultipleFilesUpload: boolean;
    attrRenderFiles: (filename: jqwidgets.FileUploadRenderFiles['fileName']) => void;
    attrRtl: boolean;
    attrTheme: string;
    attrUploadUrl: string;
    attrUploadTemplate: string;
    attrWidth: string | number;
    attrHeight: string | number;
    autoCreate: boolean;
    properties: string[];
    host: any;
    elementRef: ElementRef;
    widgetObject: jqwidgets.jqxFileUpload;
    constructor(containerElement: ElementRef);
    ngOnInit(): void;
    ngOnChanges(changes: SimpleChanges): boolean;
    arraysEqual(attrValue: any, hostValue: any): boolean;
    manageAttributes(): any;
    moveClasses(parentEl: HTMLElement, childEl: HTMLElement): void;
    moveStyles(parentEl: HTMLElement, childEl: HTMLElement): void;
    createComponent(options?: any): void;
    createWidget(options?: any): void;
    __updateRect__(): void;
    setOptions(options: any): void;
    autoUpload(arg?: boolean): boolean;
    accept(arg?: string): string;
    browseTemplate(arg?: string): string;
    cancelTemplate(arg?: string): string;
    disabled(arg?: boolean): boolean;
    fileInputName(arg?: string): string;
    height(arg?: number | string): number | string;
    localization(arg?: jqwidgets.FileUploadLocalization): jqwidgets.FileUploadLocalization;
    multipleFilesUpload(arg?: boolean): boolean;
    renderFiles(arg?: (filename: jqwidgets.FileUploadRenderFiles['fileName']) => void): (filename: jqwidgets.FileUploadRenderFiles['fileName']) => void;
    rtl(arg?: boolean): boolean;
    theme(arg?: string): string;
    uploadUrl(arg?: string): string;
    uploadTemplate(arg?: string): string;
    width(arg?: string | number): string | number;
    browse(): void;
    cancelFile(fileIndex: number): void;
    cancelAll(): void;
    destroy(): void;
    render(): void;
    refresh(): void;
    uploadFile(fileIndex: number): void;
    uploadAll(): void;
    onRemove: EventEmitter<any>;
    onSelect: EventEmitter<any>;
    onUploadStart: EventEmitter<any>;
    onUploadEnd: EventEmitter<any>;
    __wireEvents__(): void;
    static ɵfac: i0.ɵɵFactoryDeclaration<jqxFileUploadComponent, never>;
    static ɵcmp: i0.ɵɵComponentDeclaration<jqxFileUploadComponent, "jqxFileUpload", never, { "attrAutoUpload": "autoUpload"; "attrAccept": "accept"; "attrBrowseTemplate": "browseTemplate"; "attrCancelTemplate": "cancelTemplate"; "attrDisabled": "disabled"; "attrFileInputName": "fileInputName"; "attrLocalization": "localization"; "attrMultipleFilesUpload": "multipleFilesUpload"; "attrRenderFiles": "renderFiles"; "attrRtl": "rtl"; "attrTheme": "theme"; "attrUploadUrl": "uploadUrl"; "attrUploadTemplate": "uploadTemplate"; "attrWidth": "width"; "attrHeight": "height"; "autoCreate": "auto-create"; }, { "onRemove": "onRemove"; "onSelect": "onSelect"; "onUploadStart": "onUploadStart"; "onUploadEnd": "onUploadEnd"; }, never, ["*"]>;
}
