/// <reference path="../jqwidgets.d.ts" />
import { EventEmitter, ElementRef, OnChanges, SimpleChanges } from '@angular/core';
import { ControlValueAccessor } from '@angular/forms';
import * as i0 from "@angular/core";
export declare class jqxRadioButtonComponent implements ControlValueAccessor, OnChanges {
    attrAnimationShowDelay: number;
    attrAnimationHideDelay: number;
    attrBoxSize: number | string;
    attrChecked: boolean;
    attrDisabled: boolean;
    attrEnableContainerClick: boolean;
    attrGroupName: string;
    attrHasThreeStates: boolean;
    attrRtl: boolean;
    attrTheme: string;
    attrWidth: string | number;
    attrHeight: string | number;
    autoCreate: boolean;
    properties: string[];
    valueAttr: any;
    host: any;
    elementRef: ElementRef;
    widgetObject: jqwidgets.jqxRadioButton;
    private onTouchedCallback;
    private onChangeCallback;
    constructor(containerElement: ElementRef);
    ngOnInit(): void;
    ngOnChanges(changes: SimpleChanges): boolean;
    arraysEqual(attrValue: any, hostValue: any): boolean;
    manageAttributes(): any;
    moveClasses(parentEl: HTMLElement, childEl: HTMLElement): void;
    moveStyles(parentEl: HTMLElement, childEl: HTMLElement): void;
    createComponent(options?: any): void;
    createWidget(options?: any): void;
    __updateRect__(): void;
    writeValue(value: any): void;
    registerOnChange(fn: any): void;
    registerOnTouched(fn: any): void;
    setOptions(options: any): void;
    animationShowDelay(arg?: number): number;
    animationHideDelay(arg?: number): number;
    boxSize(arg?: number | string): number | string;
    checked(arg?: boolean): boolean;
    disabled(arg?: boolean): boolean;
    enableContainerClick(arg?: boolean): boolean;
    groupName(arg?: string): string;
    hasThreeStates(arg?: boolean): boolean;
    height(arg?: string | number): string | number;
    rtl(arg?: boolean): boolean;
    theme(arg?: string): string;
    width(arg?: string | number): string | number;
    check(): void;
    disable(): void;
    destroy(): void;
    enable(): void;
    focus(): void;
    render(): void;
    uncheck(): void;
    val(value?: boolean): any;
    onChecked: EventEmitter<any>;
    onChange: EventEmitter<any>;
    onUnchecked: EventEmitter<any>;
    __wireEvents__(): void;
    static ɵfac: i0.ɵɵFactoryDeclaration<jqxRadioButtonComponent, never>;
    static ɵcmp: i0.ɵɵComponentDeclaration<jqxRadioButtonComponent, "jqxRadioButton", never, { "attrAnimationShowDelay": "animationShowDelay"; "attrAnimationHideDelay": "animationHideDelay"; "attrBoxSize": "boxSize"; "attrChecked": "checked"; "attrDisabled": "disabled"; "attrEnableContainerClick": "enableContainerClick"; "attrGroupName": "groupName"; "attrHasThreeStates": "hasThreeStates"; "attrRtl": "rtl"; "attrTheme": "theme"; "attrWidth": "width"; "attrHeight": "height"; "autoCreate": "auto-create"; }, { "onChecked": "onChecked"; "onChange": "onChange"; "onUnchecked": "onUnchecked"; }, never, ["*"]>;
}
